### ISSUE TITLE
Problem about the npy file?

### ISSUE THREAD

**Issue by joyivan** [ShahinSHH/COVID-CT-MD#5]
I use the numpy load() to read the npy file, and the Slice-level-labels.npy has no problem, but the updated Slice-level-labels-updated-1.npy file has the problem reported like this:
 `return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '\x0a'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/***/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 423, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file 'Slice-level-labels-updated-1.npy' as a pickle
`
I also switch the allow_pickle para in the load() method,but  Both attempts failed.
thanks for sharing the data

**Comment by joyivan** [comment]
```
 raise ValueError("Cannot load file containing pickled data " 
ValueError: Cannot load file containing pickled data when allow_pickle=False  `
```
when I turn the allow_pickle para to False

**Comment by joyivan** [comment]
I have solve the problem
